### ISSUE TITLE
Version: 0.1.3 - source folder always comes back with ./

### ISSUE THREAD

**Issue by baronmor** [kirkone/vsts-dnx-tasks#19] opened 2016-07-12 01:14 UTC
Tried to use the DNX Tasks Build Web, but run into an error where the script adds ./ in front of the source directory even when I provide fully qualified path e.g. ".\F:\agent_work\57\s\xxx\Service\project.json". To be clear I tried relative path but the script BuildWebPackage.ps1 keeps inserting ./ no matter what.

**Comment by kirkone** [comment] 2016-07-12 12:58
You are right, the path is always relative to the `Working Folder`.
If you do not have the `src` folder you can leave this field blank.
I did not think about absolute paths here. Can you please explain why you need to specify an absolute path here?
I will try to get this working with your requirements.

Greetings,
KirK

**Comment by baronmor** [comment] 2016-07-13 00:30
when leaving the source folder blank I'm getting the following error:
 Cannot bind argument to parameter 'Path' because it is an empty string

**Comment by baronmor** [comment] 2016-07-13 00:33
I don't necessarily need to use an absolute path, I was trying it because the relative path does not work. When I tested on the build agent directly with a fully qualified path and it did work

**Comment by ADWILS-MSFT** [comment] 2016-07-14 01:17
I think the problem here is that VSTS allows you to use a full qualified path, but your scripts do not check for fully qualified paths and instead enforce .\ on everything regardless of input.

**Comment by kirkone** [comment] 2016-07-15 07:22
Hi,

an empty path should be ok for this. But it does not work. I will do some work on this in the next days.
So hopefully this is fixed in a short amout of time.

Thanks for the Feedback.

KirK

**Comment by kirkone** [comment] 2016-07-18 06:46
Hi,

I did some work on this issue and published a new version of the extension.
There is now a check if the given path is an absolute path. Also the empty field should now work as intended.
Can you give this a try?

CU, KirK

**Closed as completed** 2017-01-16 21:23 UTC
